server:
  port: 9003

spring:
  application:
    name: inventory-service
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/inventorydb
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka